function dlg = create_progress_dialog(parent_figure, title_text)
%CREATE_PROGRESS_DIALOG Create a determinate progress dialog for run/export tasks.

dlg = uiprogressdlg(parent_figure, ...
    'Title', title_text, ...
    'Message', '0% - starting', ...
    'Value', 0, ...
    'Indeterminate', 'off', ...
    'Cancelable', 'off');
drawnow;
end
