export_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(fileparts(export_dir));
addpath(genpath(project_root));
params = struct();
params.motionType = 'circular';
params.sliceType = 'xy';
params.partType = 'tot';
params.fieldType = 'E_mag';
params.a_over_lambda = 1.2;
params.beta_max = 0.6;
params.slicePos_over_lambda = 0;
params.phase_over_T = 0;
params.cmapMode = 'log';
params.outputMode = 'image+video';
params.exportAllFields = false;
params.viewMode = 'custom';
params.customFields = {'E_mag', 'B_mag', 'E_stream', 'S_stream'};
params.selectedFields = {'E_mag', 'B_mag', 'E_stream', 'S_stream'};
run_moving_charge_generation('export', params, project_root);
