function main
project_root = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(project_root));
addpath(fullfile(repo_root, 'utils'));
addpath(genpath(fullfile(project_root, 'app')));
addpath(genpath(fullfile(project_root, 'core')));
addpath(genpath(fullfile(project_root, 'docs')));

tab_builders = { ...
    @(tab_group, root) create_domain_tab(tab_group, root, 'art', 'Art', ...
        'Visual, decorative, and scene-based MATLAB artworks.'), ...
    @(tab_group, root) create_domain_tab(tab_group, root, 'fractals', 'Fractals', ...
        'Escape-time fractals, recursive geometry, IFS forms, and fractal fields.'), ...
    @(tab_group, root) create_domain_tab(tab_group, root, 'nonlinear', 'Nonlinear', ...
        'Nonlinear dynamics, chaotic attractors, maps, oscillators, and reaction waves.')};

launch_gui_studio(project_root, tab_builders, 'StudioName', 'Creative Plot Studio');
end
