from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from matplotlib import pyplot as plt

from projects.Waveguide.core import model
from projects.Waveguide.core.metal import circular_metal_field
from utils import image_output
from utils.image_output import write_manifest


PROJECT = "Waveguide"


def _format_value(value: object) -> str:
    if isinstance(value, (list, tuple)):
        if value and isinstance(value[0], (list, tuple)):
            rows = [" ".join(str(item) for item in row) for row in value]
            return "[" + ";".join(rows) + "]"
        return "[" + " ".join(str(item) for item in value) + "]"
    return str(value)


def _write_parameters(folder: Path, params: dict[str, object]) -> Path:
    lines = ["Generated by Python reproduction", ""]
    lines.extend(f"{key} = {_format_value(value)}" for key, value in params.items())
    path = folder / "parameters.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _write_reproduce_code(folder: Path, example: str) -> Path:
    path = folder / "reproduce_code.py"
    path.write_text(
        "from projects.Waveguide.example.reproduction import main\n\n"
        f"if __name__ == '__main__':\n    main('{example}')\n",
        encoding="utf-8",
    )
    return path


def _export_named_figures(bundle, folder: Path, names: Iterable[str]) -> list[Path]:
    paths: list[Path] = []
    for fig, name in zip(bundle.figures, names):
        paths.append(image_output.save_figure(fig, folder, name, title_band=None))
    if len(paths) > 1:
        paths.append(image_output.compose_grid(paths, folder / "composite.png"))
    plt.close("all")
    return paths


def rectangle_te(output: str | Path | None = None) -> list[Path]:
    folder = image_output.ensure_dir(output or Path(__file__).parent / "rectangle_TE")
    modes = [(m, n) for m in range(1, 4) for n in range(0, 4)]
    params = {
        "guide": "rectangular",
        "waveguide_kind": "metal",
        "action": "mode field",
        "polarization": "TE",
        "mode_type": "TE",
        "modes": ";".join(f"({m},{n})" for m, n in modes),
        "grid_n": 240,
        "samples": 260,
        "a": 0.03,
        "xi0": 0.5,
        "b": 0.015,
        "mode_matrix": modes,
    }
    bundle = model.render(params)
    names = [f"{index:02d}_te_rectangular_m{m}_n{n}.png" for index, (m, n) in enumerate(modes, start=1)]
    outputs = _export_named_figures(bundle, folder, names)
    outputs.extend([_write_parameters(folder, params), _write_reproduce_code(folder, "rectangle_TE")])
    outputs.append(write_manifest(folder, PROJECT, "rectangle_TE", [params], outputs, bundle.report))
    return outputs


def planar_te(output: str | Path | None = None) -> list[Path]:
    folder = image_output.ensure_dir(output or Path(__file__).parent / "planar_TE")
    orders = list(range(4))
    params = {
        "waveguide_kind": "planar",
        "action": "mode field",
        "polarization": "TE",
        "mode_type": "TE",
        "orders": "(0:3)",
        "grid_n": 240,
        "samples": 260,
        "vmax": 12,
        "frequency_ghz": 12,
        "freq_ghz": 12,
        "z_length": 0.1,
        "nco": 1.5,
        "ncl": 1.45,
        "n1": 1.5,
        "n2": 1.45,
        "d": 0.1,
        "order_list": orders,
    }
    bundle = model.render(params)
    names = [f"{index:02d}_te_planar_order{order}.png" for index, order in enumerate(orders, start=1)]
    outputs = _export_named_figures(bundle, folder, names)
    outputs.extend([_write_parameters(folder, params), _write_reproduce_code(folder, "planar_TE")])
    outputs.append(write_manifest(folder, PROJECT, "planar_TE", [params], outputs, bundle.report))
    return outputs


def annulus_tm(output: str | Path | None = None) -> list[Path]:
    folder = image_output.ensure_dir(output or Path(__file__).parent / "annulus_TM")
    modes = [(m, n) for m in range(1, 4) for n in range(1, 5)]
    params = {
        "guide": "annulus",
        "waveguide_kind": "metal",
        "action": "mode field",
        "polarization": "TM",
        "mode_type": "TM",
        "modes": ";".join(f"({m},{n})" for m, n in modes),
        "grid_n": 240,
        "samples": 260,
        "xi0": 0.5,
        "radius": 0.03,
        "mode_matrix": modes,
    }
    bundle = model.render(params)
    names = [f"{index:02d}_tm_annular_m{m}_n{n}.png" for index, (m, n) in enumerate(modes, start=1)]
    outputs = _export_named_figures(bundle, folder, names)
    outputs.extend([_write_parameters(folder, params), _write_reproduce_code(folder, "annulus_TM")])
    outputs.append(write_manifest(folder, PROJECT, "annulus_TM", [params], outputs, bundle.report))
    return outputs


def annulus_invariant() -> dict[str, object]:
    field = circular_metal_field("TM", 1, 1, 0.03, 120, 0.5)
    return {
        "shape": field["field"].shape,
        "fc_ghz": field["fc_ghz"],
        "has_inner_mask": bool(field["boundary_radii"][0] == 0.5 and field["field"][60, 60] != field["field"][60, 60]),
    }


def main(example: str | None = None, output: str | Path | None = None) -> list[Path]:
    runners = {
        "rectangle_TE": rectangle_te,
        "planar_TE": planar_te,
        "annulus_TM": annulus_tm,
    }
    if example is None:
        parser = argparse.ArgumentParser()
        parser.add_argument("example", choices=sorted(runners))
        parser.add_argument("--output", type=Path)
        args = parser.parse_args()
        example = args.example
        output = args.output
    return runners[example](output)


if __name__ == "__main__":
    main()

