function dlg = create_progress_dialog(app_figure, title_text)
%CREATE_PROGRESS_DIALOG Create a standard progress dialog.

dlg = uiprogressdlg(app_figure, ...
    'Title', title_text, ...
    'Message', 'starting', ...
    'Indeterminate', 'off', ...
    'Value', 0);
end
