params = struct();
params.guide = 'rectangular';
params.action = 'mode field';
params.mode_type = 'TE';
params.legend_location = 'best';
params.map_name = 'project';
params.grid_n = 240;
params.samples = 260;
params.layout_rows = 'auto';
params.a = 0.03;
params.xi0 = 0.5;
params.b = 0.015;
params.radius = NaN;
params.mode_matrix = [1 0;1 1;1 2;1 3;2 0;2 1;2 2;2 3;3 0;3 1;3 2;3 3];
params.max_order = NaN;
params.fmax_ghz = NaN;
run_from_params(params);
