function lines = notes_catalog(family, subtype, action)
%NOTES_CATALOG Return explanatory notes for the selected waveguide page.

family = char(lower(string(family)));
subtype = char(lower(string(subtype)));
action = char(lower(string(action)));

switch family
    case 'metal'
        if strcmp(subtype, 'rectangular')
            base = {'Rectangular PEC waveguide: width a, height b, and perfectly conducting walls.'; ...
                'Mode indices (m,n) count the transverse half-waves. TE can use m=0 or n=0, but not both; TM requires m>=1 and n>=1.'; ...
                'Cutoff frequency: f_c = (c/2)*sqrt((m/a)^2 + (n/b)^2). Below f_c that mode is evanescent.'};
        else
            base = {'Circular PEC waveguide: radius r and perfectly conducting boundary.'; ...
                'Mode index m is azimuthal order; n is radial-root order. TM uses zeros of J_m, TE uses zeros of dJ_m/dr.'; ...
                'Cutoff frequency: f_c = c*chi/(2*pi*r), where chi is the appropriate Bessel root.'};
        end
        switch action
            case 'mode field'
                lines = [base; ...
                    {'Mode-field plots show the normalized longitudinal scalar component: H_z for TE, E_z for TM.'; ...
                    'The colorbar is normalized to [-1,1], so it shows field pattern/sign rather than absolute amplitude.'; ...
                    'If you request several mode tuples at once, the multi-plot layout box can assemble them into one high-resolution sheet. Use an integer such as 4 or a row pattern like 4+4+2.'}];
            case 'dispersion curves'
                lines = [base; ...
                    {'Dispersion curves use beta = (2*pi/c)*sqrt(f^2 - f_c^2). The plot begins only where f > f_c.'; ...
                    'The left axis is phase constant beta in rad/m; the right axis is normalized group velocity v_g/c = sqrt(1 - (f_c/f)^2).'; ...
                    'The f max (GHz) box sets the upper frequency shown. Default 10 GHz is enough for ordinary low-order plots; increase it only if all chosen modes are above 10 GHz.'; ...
                    'Each legend entry includes that mode''s own cutoff f_c.'}];
            otherwise
                lines = [base; ...
                    {'Cutoff maps show f_c over the selected m,n index grid. Lower f_c means the mode starts propagating at a lower frequency.'; ...
                    'Blank/NaN cells are physically invalid modes, such as rectangular TM modes with m=0 or n=0.'}];
        end
    case 'planar'
        base = {'Symmetric planar dielectric slab: core index n_co, cladding index n_cl, and core thickness d.'; ...
            'Guided modes require n_co > n_cl and propagate as exp(-j beta z).'; ...
            'Effective index is n_eff = beta/k_0, where k_0 = 2*pi/lambda_0. For guided slab modes, n_cl < n_eff < n_co.'; ...
            'Normalized frequency is V = k_0*d*sqrt(n_co^2 - n_cl^2)/2. Larger V means a thicker guide, higher frequency, or stronger index contrast.'; ...
            'Normalized propagation parameter is b = (n_eff^2 - n_cl^2)/(n_co^2 - n_cl^2), so b near 0 is close to cutoff and b near 1 is strongly core-confined.'};
        switch action
            case 'mode field'
                lines = [base; ...
                    {'Mode-field plots show the transverse mode shape multiplied by cos(beta z). TE uses dominant E_y; TM uses dominant H_y.'; ...
                    'Order 0 is the fundamental slab mode; higher orders have more transverse nodes and need larger V to exist.'; ...
                    'If you request several slab orders at once, the multi-plot layout box can assemble them into one high-resolution sheet. Use an integer such as 4 or a row pattern like 4+4+2.'}];
            case 'dispersion curve'
                lines = [base; ...
                    {'The dispersion curve is b versus V. It is normalized, so it does not need a physical thickness d.'; ...
                    'After b is solved, n_eff is recovered from n_eff = sqrt(n_cl^2 + b*(n_co^2 - n_cl^2)).'; ...
                    'A branch starts at its cutoff V value; missing high-order branches mean they do not exist within V_max.'}];
            case 'mode existence'
                lines = [base; ...
                    {'Mode existence shows cutoff locations in V. A horizontal segment means that order is guided for V to the right of its cutoff.'; ...
                    'For a symmetric slab, order q approximately starts near V = q*pi/2 in this normalized convention.'}];
            otherwise
                lines = [base; ...
                    {'Thickness sweep converts d into V at the fixed frequency, then solves the guided branches.'; ...
                    'The left axis counts how many guided modes exist; the right axis shows n_eff for each branch.'}];
        end
    case 'cylindrical'
        lines = {'Cylindrical step-index dielectric waveguide: core index n_co and cladding index n_cl.'; ...
            'The normalized variables are V = k_0*a*sqrt(n_co^2 - n_cl^2), U = a*sqrt(n_co^2*k_0^2 - beta^2), and W = a*sqrt(beta^2 - n_cl^2*k_0^2).'; ...
            'They satisfy V^2 = U^2 + W^2. Guided modes have n_cl*k_0 < beta < n_co*k_0, equivalently n_cl < n_eff < n_co.'; ...
            'The contour lines mark roots of the step-index characteristic equation. Each colored contour corresponds to one azimuthal order m.'; ...
            'The dashed U=V line is the boundary W=0, i.e. cutoff.'};
    otherwise
        lines = {'No notes are available for this page.'};
end
end
