export_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(fileparts(export_dir));
addpath(genpath(project_root));
params = struct();
params.type = 'rect';
params.boundary = 'FSCS';
params.nu = 0.3;
params.n = 220;
params.normalize = true;
params.D = 0.6;
params.xi0 = 0.9;
params.a = 2;
params.b = 1.8;
params.load_type = 'points';
params.q0 = 0;
params.kmodes = 60;
params.mmax = 60;
params.distribution_samples = 15;
params.draw_zero_contour = false;
params.sources = [-0.2 -0.6 -0.6 0;0.45 0.25 0.1 0.04];
compute_static_sources(params);
